-- union 2 results: MIN() and MAX()
SELECT NAME, BIRTHDAY, 'YOUNGEST' AS TYPE
FROM worker
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY) 
    FROM worker
)
UNION
SELECT NAME, BIRTHDAY, 'ELDEST' AS TYPE
FROM worker
WHERE BIRTHDAY = (
    SELECT MIN(BIRTHDAY) 
    FROM worker
);